### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by yaomtc** [chaotic-aur/pkgbuild-ki18n-git#4]
```
[ 40%] Built target KF5I18n
[ 43%] Generating sip/PyKF5/KI18n/klocalizedcontext.sip
[ 45%] Generating sip/PyKF5/KI18n/klocalizedstring.sip
[ 47%] Generating sip/PyKF5/KI18n/klocalizedtranslator.sip
[ 50%] Generating sip/PyKF5/KI18n/kuitmarkup.sip
[ 52%] Generating sip/PyKF5/KI18n/kuitsetup.sip
[ 52%] Built target generate_KI18n_sip_files
[ 54%] Generating pybuild/PyKF5/KI18n/unifiedKI18n.cpp
sip: /usr/lib/python3.9/site-packages/PyQt5/bindings/QtCore/QtCoremod.sip:23: syntax error
make[2]: *** [src/i18n/CMakeFiles/sip_generated_KI18n_files.dir/build.make:77: src/i18n/pybuild/PyKF5/KI18n/unifiedKI18n.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:324: src/i18n/CMakeFiles/sip_generated_KI18n_files.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Build failed with exit code 4 in /home/chris/.cache/rua/build/ki18n-git
```

Also referenced in the comments for kcoreaddons-git: https://aur.archlinux.org/packages/kcoreaddons-git

**Comment by IslandC0der** [comment]
Do you have `python2` installed?

**Comment by yaomtc** [comment]
I do not.

**Comment by IslandC0der** [comment]
Hi, can you still reproduce?
It has supposedly been [fixed upstream](https://bugs.kde.org/show_bug.cgi?id=444857).

**Comment by yaomtc** [comment]
Hmm. I'm not getting that particular error anymore, but now I'm getting a different issue... When I try to build `plasma-workspace-git` it lists (among other things) `kde-cli-tools-git` as a dependency. When I try to build `kde-cli-tools-git`, it gives me an error about an unmet dependency... `plasma-workspace-git`

**Comment by IslandC0der** [comment]
Alrighty :)

Regarding the circular dependency, build `plasma-workspace-git` by doing the following: manually install its make dependencies and dependencies (except `kde-cli-tools-git`), then run `makepkg` with the `-id` flags. At this point, you can remove all those dependencies and compile `kde-cli-tools-git` normally.
You will only need to do this the first time you compile these packages; when they already exist on your system and you want to rebuild to update, you won't have issues.

**Comment by yaomtc** [comment]
Here is the error at the end when I run `makepkg -id` in the `kde-cli-tools-git` folder.

```
CMake Error at CMakeLists.txt:61 (find_package):
  Could not find a configuration file for package "LibKWorkspace" that is
  compatible with requested version "5.23.80".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/LibKWorkspace/LibKWorkspaceConfig.cmake, version: 5.23.3
    /usr/lib/cmake/LibKWorkspace/LibKWorkspaceConfig.cmake, version: 5.23.3
    /lib64/cmake/LibKWorkspace/LibKWorkspaceConfig.cmake, version: 5.23.3
    /lib/cmake/LibKWorkspace/LibKWorkspaceConfig.cmake, version: 5.23.3



-- Configuring incomplete, errors occurred!
See also "/home/chris/Software/kde-cli-tools-git/src/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by IslandC0der** [comment]
No, see my comment: you're supposed to run `makepkg -id` to compile `plasma-workspace-git` first, after manually installing its dependencies.

That means you'll run that command on the `plasma-workspace-git` folder after installing these packages:
``
knotifyconfig-git libksysguard-git ktexteditor-git libqalculate appstream-qt phonon-qt5-git xorg-xrdb xorg-xsetroot kactivitymanagerd-git kholidays-git xorg-xmessage milou-git prison-git kwin-git plasma-integration-git kdelibs4support-git kpeople-git kactivities-stats-git libkscreen-git kquickcharts-git kuserfeedback-git layer-shell-qt-git git extra-cmake-modules-git kdoctools-git gpsd baloo-git networkmanager-qt-git kdesignerplugin-git kinit-git plasma-wayland-protocols-git
``

If you don't want to do that, you can also just remove `kde-cli-tools-git` from the `depends()` array for `plasma-workspace-git` and compile it as usual (but make sure to add it back afterwards, so that the `pacman` database gets corrected the next time you compile it).

Then, you can compile `kde-cli-tools-git` normally :)

**Comment by yaomtc** [comment]
Ah, I misunderstood, thanks.
